# Generated by Django 5.2.15 on 2026-07-16 13:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        ("education", "0001_initial"),
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Не начато"),
                            ("attempted", "Была попытка"),
                            ("solved", "Решено"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("attempts_count", models.PositiveIntegerField(default=0, verbose_name="Количество попыток")),
                ("best_score", models.PositiveIntegerField(default=0, verbose_name="Лучший балл")),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Максимальный балл",
                    ),
                ),
                (
                    "last_submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата последней отправки"),
                ),
                ("solved_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата решения")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "best_submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="best_for_progress_records",
                        to="submissions.submission",
                        verbose_name="Лучшая отправка",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="assessments.exercise",
                        verbose_name="Задание",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_progress_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс задания",
                "verbose_name_plural": "Прогресс заданий",
                "ordering": (
                    "student",
                    "exercise__lesson__module__course",
                    "exercise__lesson__order",
                    "exercise__order",
                ),
                "indexes": [models.Index(fields=["student", "status"], name="exercise_prog_student_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("student", "exercise"), name="uniq_exercise_progress")
                ],
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Не начат"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершён"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "last_opened_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата последнего открытия"),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата завершения")),
                (
                    "time_spent_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Потрачено времени, секунд",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="education.lesson",
                        verbose_name="Урок",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс урока",
                "verbose_name_plural": "Прогресс уроков",
                "ordering": ("student", "lesson__module__course", "lesson__module__order", "lesson__order"),
                "indexes": [models.Index(fields=["student", "status"], name="lesson_prog_student_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("student", "lesson"), name="uniq_lesson_progress")
                ],
            },
        ),
    ]
