# Generated by Django 5.2.15 on 2026-07-16 12:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.TextField(verbose_name="Код решения")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "В очереди"),
                            ("running", "Проверяется"),
                            ("accepted", "Принято"),
                            ("wrong_answer", "Неверный ответ"),
                            ("runtime_error", "Ошибка выполнения"),
                            ("time_limit_exceeded", "Превышен лимит времени"),
                            ("memory_limit_exceeded", "Превышен лимит памяти"),
                            ("internal_error", "Внутренняя ошибка проверки"),
                        ],
                        default="queued",
                        max_length=40,
                        verbose_name="Статус",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0, verbose_name="Полученные баллы")),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Максимальный балл",
                    ),
                ),
                ("passed_tests", models.PositiveIntegerField(default=0, verbose_name="Пройдено тестов")),
                ("total_tests", models.PositiveIntegerField(default=0, verbose_name="Всего тестов")),
                (
                    "execution_time_ms",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Время выполнения, мс"),
                ),
                (
                    "memory_used_mb",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Использовано памяти, МБ"
                    ),
                ),
                ("stdout", models.TextField(blank=True, default="", verbose_name="Стандартный вывод")),
                ("stderr", models.TextField(blank=True, default="", verbose_name="Стандартный поток ошибок")),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="Сообщение об ошибке"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата отправки")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("checked_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата проверки")),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="assessments.exercise",
                        verbose_name="Задание",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отправка решения",
                "verbose_name_plural": "Отправки решений",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TestCaseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Пройден"),
                            ("failed", "Не пройден"),
                            ("error", "Ошибка"),
                            ("skipped", "Пропущен"),
                        ],
                        default="skipped",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("input_data", models.TextField(blank=True, default="", verbose_name="Входные данные")),
                ("expected_output", models.TextField(blank=True, default="", verbose_name="Ожидаемый вывод")),
                ("actual_output", models.TextField(blank=True, default="", verbose_name="Фактический вывод")),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="Сообщение об ошибке"),
                ),
                (
                    "execution_time_ms",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Время выполнения, мс"),
                ),
                (
                    "memory_used_mb",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Использовано памяти, МБ"
                    ),
                ),
                ("points_awarded", models.PositiveIntegerField(default=0, verbose_name="Начисленные баллы")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="submissions.submission",
                        verbose_name="Отправка решения",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="assessments.testcase",
                        verbose_name="Тест-кейс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат тест-кейса",
                "verbose_name_plural": "Результаты тест-кейсов",
                "ordering": ("submission", "test_case__order"),
            },
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["student", "exercise", "-created_at"], name="sub_student_ex_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["status", "-created_at"], name="sub_status_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="testcaseresult",
            constraint=models.UniqueConstraint(
                fields=("submission", "test_case"), name="uniq_result_submission_test"
            ),
        ),
    ]
