# Generated by Django 6.0.4 on 2026-05-01 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='tabel',
            new_name='table',
        ),
    ]
