# Generated by Django 6.0.4 on 2026-05-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('image', models.ImageField(upload_to='table_image/')),
                ('seats', models.IntegerField()),
                ('description', models.TextField()),
                ('is_free', models.BooleanField(default=True)),
            ],
        ),
    ]
