# Generated by Django 5.2.15 on 2026-07-16 12:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, blank=True, max_length=220, verbose_name="URL-имя"),
                ),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=255, verbose_name="Краткое описание"),
                ),
                ("statement", models.TextField(verbose_name="Условие задания")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "Лёгкая"), ("medium", "Средняя"), ("hard", "Сложная")],
                        default="easy",
                        max_length=20,
                        verbose_name="Сложность",
                    ),
                ),
                (
                    "check_strategy",
                    models.CharField(
                        choices=[
                            ("stdin_stdout", "Проверка через stdin/stdout"),
                            ("unit_test", "Проверка через unit-тесты"),
                        ],
                        default="stdin_stdout",
                        max_length=30,
                        verbose_name="Способ проверки",
                    ),
                ),
                ("starter_code", models.TextField(blank=True, default="", verbose_name="Стартовый код")),
                (
                    "reference_solution",
                    models.TextField(blank=True, default="", verbose_name="Эталонное решение"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Максимальный балл",
                    ),
                ),
                (
                    "time_limit_ms",
                    models.PositiveIntegerField(
                        default=2000,
                        validators=[django.core.validators.MinValueValidator(100)],
                        verbose_name="Лимит времени, мс",
                    ),
                ),
                (
                    "memory_limit_mb",
                    models.PositiveIntegerField(
                        default=128,
                        validators=[django.core.validators.MinValueValidator(16)],
                        verbose_name="Лимит памяти, МБ",
                    ),
                ),
                ("is_published", models.BooleanField(default=False, verbose_name="Опубликовано")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="education.lesson",
                        verbose_name="Урок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задание",
                "verbose_name_plural": "Задания",
                "ordering": ("lesson__module__course", "lesson__module__order", "lesson__order", "order"),
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120, verbose_name="Название")),
                ("input_data", models.TextField(blank=True, verbose_name="Входные данные")),
                ("expected_output", models.TextField(verbose_name="Ожидаемый вывод")),
                ("is_hidden", models.BooleanField(default=False, verbose_name="Скрытый тест")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Баллы",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="assessments.exercise",
                        verbose_name="Задание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тест-кейс",
                "verbose_name_plural": "Тест-кейсы",
                "ordering": ("exercise", "order"),
            },
        ),
        migrations.AddConstraint(
            model_name="exercise",
            constraint=models.UniqueConstraint(
                fields=("lesson", "order"), name="unique_exercise_order_per_lesson"
            ),
        ),
        migrations.AddConstraint(
            model_name="exercise",
            constraint=models.UniqueConstraint(
                fields=("lesson", "slug"), name="unique_exercise_slug_per_lesson"
            ),
        ),
        migrations.AddConstraint(
            model_name="testcase",
            constraint=models.UniqueConstraint(
                fields=("exercise", "order"), name="unique_test_case_order_per_exercise"
            ),
        ),
    ]
